# This file should be considered public domain
################################################################################
## # # # # # # # # # # # # ## DO NOT EDIT THIS FILE ## # # # # # # # # # # # ###
################################################################################
# IF YOU WISH TO MAKE CHANGES, COPY THIS FILE TO ./config_local.py AND APPLY
# THE CHANGES, THEN RESTART THE APPLICATION.
################################################################################
import os
import bcrypt

REPO_ROOT = os.path.dirname(__file__)

# This generates a different salt every time you start the application.
# This means that session cookies will expire. For production deployments you
# should consider replacing this with
# SECRET_KEY = 'your-own-custom-secret-salt'
SECRET_KEY = bcrypt.gensalt()

SQLALCHEMY_DATABASE_URI = 'sqlite:///{0}/talkatv.db'.format(
        REPO_ROOT)

OPENID_FS_STORE_PATH = os.path.join(REPO_ROOT, 'openid-data')

WSGI_BIND_ADDR = '127.0.0.1', 45474

CORS_ALLOW_ORIGIN = '*'
CORS_MAX_AGE = 3600
CORS_ALLOW_HEADERS = 'Accept, Content-Type, Connection, Cookie'
CORS_ALLOW_METHODS = 'GET, POST'
CORS_ALLOW_CREDENTIALS = 'true'

# EMAIL
NOTIFICATION_ADDR = 'notifications@talka.tv'

# SMTP
SMTP_SSL = False
SMTP_HOST = 'localhost'
SMTP_PORT = None  # None == use default port
SMTP_USER = ''
SMTP_PASS = ''
